source 'https://rubygems.org'

ruby '2.3.0'

gem 'rails', '4.2.5'
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'compass-rails', github: 'Compass/compass-rails', branch: 'master'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'unicorn'
gem 'therubyracer'
gem 'less-rails', git: 'git://github.com/metaskills/less-rails.git'
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'autoprefixer-rails'
gem 'bootstrap-generators', '~> 3.3.4'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'simple_form'
gem 'mysql2', '~> 0.3.13'
gem 'redcarpet'
gem 'rails_12factor'
gem 'gemoji'

group :development, :test do
  gem 'annotate'
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'pry-doc'
end
