default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: nasulog_development
  username: root
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV['DEVELOPMENT_DATABASE_HOST'] || "127.0.0.1" %>
  port: <%= ENV['MYSQL_EXTERNAL_PORT'] || "3306" %>

test:
  <<: *default
  database: nasulog_test
  username: root
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV['DEVELOPMENT_DATABASE_HOST'] || "127.0.0.1" %>
  port: <%= ENV['MYSQL_EXTERNAL_PORT'] || "3306" %>

production:
  <<: *default
  url: <%= ENV["PRODUCTION_DATABASE_URL"] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
