development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nasulog_development
  pool: 5
  username: nasulog_dev
  password: nasulog_dev
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nasulog_test
  pool: 5
  username: nasulog_dev
  password: nasulog_dev
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: nasulog_production
  pool: 5
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: localhost
