default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5

development:
  <<: *default
  database: nasulog_development
  socket: /tmp/mysql.sock
  username: root

test:
  <<: *default
  database: nasulog_test
  socket: /tmp/mysql.sock
  username: root

production:
  <<: *default
  url: <%= ENV["PRODUCTION_DATABASE_URL"] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
